In [ ]:
!pip install transformers

In [2]:
import torch
from transformers import BertModel, BertTokenizer

In [3]:
model_name = 'bert-base-uncased'


In [ ]:
model = BertModel.from_pretrained(model_name, output_hidden_states=True)

In [14]:
tokenizer = BertTokenizer.from_pretrained(model_name)

In [15]:
text = 'This is a test sentence'

In [16]:
inputs = tokenizer(text,return_tensors='pt')

In [17]:
inputs['input_ids']

tensor([[ 101, 2023, 2003, 1037, 3231, 6251,  102]])

In [18]:
tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])

['[CLS]', 'this', 'is', 'a', 'test', 'sentence', '[SEP]']

In [19]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

# forward

In [20]:
model.eval()

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [21]:
with torch.no_grad():
  output = model(**inputs)

In [22]:
output

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.1276,  0.1170, -0.0797,  ..., -0.4029,  0.1983,  0.6898],
         [-0.7166, -0.4734, -0.0419,  ..., -0.6309,  0.5737,  0.6857],
         [-0.3594, -0.4751,  0.4444,  ..., -0.3402,  0.1128,  1.0230],
         ...,
         [ 0.5048, -0.4322, -0.2758,  ..., -0.5477,  0.0312, -0.3804],
         [-0.2744, -0.1734, -0.4679,  ...,  0.3030,  0.0412, -0.1826],
         [ 0.6264,  0.0517, -0.5116,  ...,  0.2888, -0.8344, -0.2331]]]), pooler_output=tensor([[-9.0331e-01, -2.7865e-01,  3.0001e-01,  7.0174e-01,  3.0519e-02,
         -2.0994e-01,  8.9889e-01,  2.0366e-01,  1.1362e-01, -9.9993e-01,
          1.6139e-01,  3.3005e-01,  9.8285e-01, -2.8164e-01,  9.1529e-01,
         -6.1660e-01, -9.2029e-02, -5.2068e-01,  3.6456e-01, -7.6548e-01,
          5.8431e-01,  9.8742e-01,  7.0894e-01,  2.4726e-01,  3.2758e-01,
          4.2558e-01, -5.8370e-01,  9.2687e-01,  9.5149e-01,  7.1230e-01,
         -7.4078e-01,  1.7453e-01, -

In [24]:
print(output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.1276,  0.1170, -0.0797,  ..., -0.4029,  0.1983,  0.6898],
         [-0.7166, -0.4734, -0.0419,  ..., -0.6309,  0.5737,  0.6857],
         [-0.3594, -0.4751,  0.4444,  ..., -0.3402,  0.1128,  1.0230],
         ...,
         [ 0.5048, -0.4322, -0.2758,  ..., -0.5477,  0.0312, -0.3804],
         [-0.2744, -0.1734, -0.4679,  ...,  0.3030,  0.0412, -0.1826],
         [ 0.6264,  0.0517, -0.5116,  ...,  0.2888, -0.8344, -0.2331]]]), pooler_output=tensor([[-9.0331e-01, -2.7865e-01,  3.0001e-01,  7.0174e-01,  3.0519e-02,
         -2.0994e-01,  8.9889e-01,  2.0366e-01,  1.1362e-01, -9.9993e-01,
          1.6139e-01,  3.3005e-01,  9.8285e-01, -2.8164e-01,  9.1529e-01,
         -6.1660e-01, -9.2029e-02, -5.2068e-01,  3.6456e-01, -7.6548e-01,
          5.8431e-01,  9.8742e-01,  7.0894e-01,  2.4726e-01,  3.2758e-01,
          4.2558e-01, -5.8370e-01,  9.2687e-01,  9.5149e-01,  7.1230e-01,
         -7.4078e-01,  1.7453e-01, -

In [25]:
output[1].shape

torch.Size([1, 768])

In [26]:
output[1]

tensor([[-9.0331e-01, -2.7865e-01,  3.0001e-01,  7.0174e-01,  3.0519e-02,
         -2.0994e-01,  8.9889e-01,  2.0366e-01,  1.1362e-01, -9.9993e-01,
          1.6139e-01,  3.3005e-01,  9.8285e-01, -2.8164e-01,  9.1529e-01,
         -6.1660e-01, -9.2029e-02, -5.2068e-01,  3.6456e-01, -7.6548e-01,
          5.8431e-01,  9.8742e-01,  7.0894e-01,  2.4726e-01,  3.2758e-01,
          4.2558e-01, -5.8370e-01,  9.2687e-01,  9.5149e-01,  7.1230e-01,
         -7.4078e-01,  1.7453e-01, -9.8497e-01, -2.0716e-01, -1.1139e-01,
         -9.8666e-01,  2.0497e-01, -7.5613e-01, -2.9575e-02, -2.5162e-02,
         -9.0826e-01,  3.4805e-01,  9.9910e-01, -3.8270e-01,  1.4600e-01,
         -3.4043e-01, -9.9998e-01,  2.0879e-01, -8.8960e-01, -1.8974e-01,
         -8.0350e-03, -2.9763e-01,  1.6387e-01,  3.9865e-01,  4.3472e-01,
          1.8029e-01, -4.6765e-02,  2.1845e-01, -1.7538e-01, -5.4732e-01,
         -5.7413e-01,  2.8072e-01,  6.7466e-02, -9.1414e-01, -1.9075e-01,
         -3.9710e-01, -4.6489e-02, -2.

In [27]:
output[0].shape

torch.Size([1, 7, 768])

In [30]:
output[0][0][0, :]

torch.Size([768])

In [31]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [34]:
my_output=model.pooler.dense(output[0][0][0, :])

In [35]:
model.pooler.activation(my_output)

tensor([-9.0331e-01, -2.7865e-01,  3.0001e-01,  7.0174e-01,  3.0519e-02,
        -2.0994e-01,  8.9889e-01,  2.0366e-01,  1.1362e-01, -9.9993e-01,
         1.6139e-01,  3.3005e-01,  9.8285e-01, -2.8164e-01,  9.1529e-01,
        -6.1660e-01, -9.2029e-02, -5.2068e-01,  3.6456e-01, -7.6548e-01,
         5.8431e-01,  9.8742e-01,  7.0894e-01,  2.4726e-01,  3.2758e-01,
         4.2558e-01, -5.8370e-01,  9.2687e-01,  9.5149e-01,  7.1230e-01,
        -7.4078e-01,  1.7453e-01, -9.8497e-01, -2.0716e-01, -1.1139e-01,
        -9.8666e-01,  2.0497e-01, -7.5613e-01, -2.9575e-02, -2.5162e-02,
        -9.0826e-01,  3.4805e-01,  9.9910e-01, -3.8270e-01,  1.4600e-01,
        -3.4043e-01, -9.9998e-01,  2.0879e-01, -8.8960e-01, -1.8974e-01,
        -8.0350e-03, -2.9763e-01,  1.6387e-01,  3.9865e-01,  4.3472e-01,
         1.8029e-01, -4.6765e-02,  2.1845e-01, -1.7538e-01, -5.4732e-01,
        -5.7413e-01,  2.8072e-01,  6.7466e-02, -9.1414e-01, -1.9075e-01,
        -3.9710e-01, -4.6489e-02, -2.4308e-01, -9.8

In [36]:
output[1] == model.pooler.activation(my_output)

tensor([[True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, T

# head