In [ ]:
!pip install transformers

In [8]:
import torch
from transformers import BertModel, BertTokenizer, BertForMaskedLM

In [4]:
model_name = 'bert-base-uncased'

In [18]:
tokenizer = BertTokenizer.from_pretrained(model_name)

In [ ]:
bert = BertModel.from_pretrained(model_name,output_hidden_states=True)

In [ ]:
mlm = BertForMaskedLM.from_pretrained(model_name,output_hidden_states=True)

In [10]:
bert

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [11]:
mlm

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_a

In [15]:
text = ("After Abraham Lincoln won the November 1860 presidential "
        "election on an anti-slavery platform, an initial seven "
        "slave states declared their secession from the country "
        "to form the Confederacy. War broke out in April 1861 "
        "when secessionist forces attacked Fort Sumter in South "
        "Carolina, just over a month after Lincoln's "
        "inauguration.")

In [16]:
text

"After Abraham Lincoln won the November 1860 presidential election on an anti-slavery platform, an initial seven slave states declared their secession from the country to form the Confederacy. War broke out in April 1861 when secessionist forces attacked Fort Sumter in South Carolina, just over a month after Lincoln's inauguration."

In [19]:
inputs = tokenizer(text,return_tensors='pt')

In [20]:
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [21]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['input_ids'][0]))

"[CLS] after abraham lincoln won the november 1860 presidential election on an anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . war broke out in april 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just over a month after lincoln ' s inauguration . [SEP]"

# mask

In [23]:
inputs['labels'] = inputs['input_ids'].detach().clone()

In [24]:
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([

In [25]:
mask = torch.rand(inputs['input_ids'].shape) < 0.15

In [26]:
mask

tensor([[ True, False,  True, False, False, False, False, False, False, False,
         False, False, False, False, False,  True, False, False, False,  True,
         False,  True,  True, False, False, False, False, False, False,  True,
          True, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False,  True, False, False, False, False,
         False, False]])

In [27]:
sum(mask[0])

tensor(10)

In [28]:
mask_arr = torch.rand(inputs['input_ids'].shape)<0.15 \
            * (inputs['input_ids'] != 101) \
            *(inputs['input_ids'] != 102)

In [29]:
mask_arr

tensor([[False, False, False,  True, False, False, False, False, False, False,
         False, False,  True, False, False, False, False, False,  True, False,
         False, False, False, False, False, False, False, False,  True, False,
          True, False, False, False, False,  True, False, False, False, False,
         False, False, False, False,  True, False, False, False, False,  True,
         False, False,  True, False, False,  True, False, False, False,  True,
         False, False]])

In [30]:
sum(mask_arr[0])

tensor(11)

In [31]:
selection = torch.flatten(mask_arr[0].nonzero()).tolist()

In [32]:
selection

[3, 12, 18, 28, 30, 35, 44, 49, 52, 55, 59]

In [33]:
tokenizer.special_tokens_map

{'unk_token': '[UNK]',
 'sep_token': '[SEP]',
 'pad_token': '[PAD]',
 'cls_token': '[CLS]',
 'mask_token': '[MASK]'}

In [35]:
tokenizer.vocab['[MASK]']

103

In [37]:
inputs['input_ids'][0,selection] = 103

In [38]:
inputs

{'input_ids': tensor([[  101,  2044,  8181,   103,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,   103,  1011,  8864,  4132,  1010,  2019,   103,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,   103,  2433,
           103, 18179,  1012,  2162,  3631,   103,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,   103,  7680,  3334,  1999,  2148,   103,
          1010,  2074,   103,  1037,  3204,   103,  5367,  1005,  1055,   103,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([

In [39]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['input_ids'][0]))

"[CLS] after abraham [MASK] won the november 1860 presidential election on an [MASK] - slavery platform , an [MASK] seven slave states declared their secession from the country [MASK] form [MASK] confederacy . war broke [MASK] in april 1861 when secession ##ist forces attacked [MASK] sum ##ter in south [MASK] , just [MASK] a month [MASK] lincoln ' s [MASK] . [SEP]"

In [40]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['labels'][0]))

"[CLS] after abraham lincoln won the november 1860 presidential election on an anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . war broke out in april 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just over a month after lincoln ' s inauguration . [SEP]"

# forward and calculate loss

In [42]:
mlm.eval()
with torch.no_grad():
  output = mlm(**inputs)

In [44]:
output.keys()

odict_keys(['loss', 'logits', 'hidden_states'])

In [46]:
output['logits'].shape

torch.Size([1, 62, 30522])

In [48]:
output['loss']

tensor(0.6759)

In [51]:
output['hidden_states'][-1]

tensor([[[-0.2946,  0.0039, -0.2899,  ..., -0.3450,  0.0129,  0.3581],
         [-0.8444, -0.1345, -0.2204,  ..., -0.4210, -0.0370,  0.4923],
         [-0.7145,  0.0250, -0.7949,  ..., -0.6303, -0.3047,  1.0890],
         ...,
         [-0.3200,  0.3024, -0.3650,  ..., -0.5119, -0.3501, -0.0296],
         [ 0.6059,  0.0358, -0.3054,  ...,  0.1757, -0.7036, -0.2008],
         [-0.5647, -0.3445, -0.9144,  ..., -0.3509, -0.4017,  0.3351]]])

## from scratch

In [52]:
last_hidden_state  = output['hidden_states'][-1]


In [53]:
last_hidden_state

tensor([[[-0.2946,  0.0039, -0.2899,  ..., -0.3450,  0.0129,  0.3581],
         [-0.8444, -0.1345, -0.2204,  ..., -0.4210, -0.0370,  0.4923],
         [-0.7145,  0.0250, -0.7949,  ..., -0.6303, -0.3047,  1.0890],
         ...,
         [-0.3200,  0.3024, -0.3650,  ..., -0.5119, -0.3501, -0.0296],
         [ 0.6059,  0.0358, -0.3054,  ...,  0.1757, -0.7036, -0.2008],
         [-0.5647, -0.3445, -0.9144,  ..., -0.3509, -0.4017,  0.3351]]])

In [54]:
mlm

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_a

In [55]:
mlm.eval()
with torch.no_grad():
  transformered = mlm.cls.predictions.transform(last_hidden_state)
  logits = mlm.cls.predictions.decoder(transformered)

In [56]:
logits

tensor([[[ -7.1304,  -7.0557,  -7.1071,  ...,  -6.3301,  -6.2804,  -4.3603],
         [ -9.6358,  -9.4616,  -9.5832,  ...,  -9.3626,  -9.1056,  -8.7191],
         [ -8.1200,  -8.5685,  -8.0517,  ...,  -7.5411,  -7.1374,  -6.9807],
         ...,
         [ -3.6438,  -3.7520,  -3.5547,  ...,  -1.9902,  -3.6871,  -5.1364],
         [-14.0678, -14.0594, -14.0583,  ..., -10.9192, -11.2679,  -9.6648],
         [-10.9592, -11.4597, -10.9997,  ..., -10.7344,  -8.6443,  -8.4977]]])

In [57]:
output['logits']

tensor([[[ -7.1304,  -7.0557,  -7.1071,  ...,  -6.3301,  -6.2804,  -4.3603],
         [ -9.6358,  -9.4616,  -9.5832,  ...,  -9.3626,  -9.1056,  -8.7191],
         [ -8.1200,  -8.5685,  -8.0517,  ...,  -7.5411,  -7.1374,  -6.9807],
         ...,
         [ -3.6438,  -3.7520,  -3.5547,  ...,  -1.9902,  -3.6871,  -5.1364],
         [-14.0678, -14.0594, -14.0583,  ..., -10.9192, -11.2679,  -9.6648],
         [-10.9592, -11.4597, -10.9997,  ..., -10.7344,  -8.6443,  -8.4977]]])

# 5.loss

In [58]:
import torch.nn as nn

In [59]:
ce = nn.CrossEntropyLoss()

In [61]:
logits.shape

torch.Size([1, 62, 30522])

In [62]:
inputs['labels'].shape

torch.Size([1, 62])

In [65]:
inputs['labels'][0].view(-1).shape

torch.Size([62])

In [67]:
ce(logits[0],inputs['labels'][0].view(-1))

tensor(0.6759)

In [68]:
output['loss']

tensor(0.6759)

In [76]:
 pred_sentence= torch.argmax(logits[0],dim=1)#返回行方向上最大值对应的索引，按理说应该要softmax之后再取
 pred_sentence.shape

torch.Size([62])

In [73]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['input_ids'][0]))

"[CLS] after abraham [MASK] won the november 1860 presidential election on an [MASK] - slavery platform , an [MASK] seven slave states declared their secession from the country [MASK] form [MASK] confederacy . war broke [MASK] in april 1861 when secession ##ist forces attacked [MASK] sum ##ter in south [MASK] , just [MASK] a month [MASK] lincoln ' s [MASK] . [SEP]"

In [74]:
' '.join(tokenizer.convert_ids_to_tokens(inputs['labels'][0]))

"[CLS] after abraham lincoln won the november 1860 presidential election on an anti - slavery platform , an initial seven slave states declared their secession from the country to form the confederacy . war broke out in april 1861 when secession ##ist forces attacked fort sum ##ter in south carolina , just over a month after lincoln ' s inauguration . [SEP]"

In [75]:
' '.join(tokenizer.convert_ids_to_tokens(pred_sentence))

'. after abraham lincoln won the november 1860 presidential election on an anti - slavery platform , an additional seven slave states declared their secession from the country to form the confederacy . war broke out in april 1861 when secession ##ist forces attacked fort sum fort in south carolina , just over a month after lincoln s s inauguration . s'

In [77]:
len(inputs['input_ids'][0])

62